import type {Product} from "./types";
export const demoProducts:Product[]=[
{id:"bearing-6204-2rs",sku:"6204-2RS",name:"6204 Deep Groove Ball Bearing 2RS",slug:"6204-2rs",category:"Bearings",brand:"Sample catalogue",description:"Structured bearing record demonstrating dimension matching, technical filtering and enquiry flow.",featured:true,stockStatus:"Enquire",imageLabel:"6204 / 20 × 47 × 14",specs:{Bore:"20 mm",OD:"47 mm",Width:"14 mm",Seal:"2RS",Clearance:"C0",Family:"Deep Groove"}},
{id:"bearing-6204-zz",sku:"6204-ZZ",name:"6204 Deep Groove Ball Bearing ZZ",slug:"6204-zz",category:"Bearings",brand:"Sample catalogue",description:"Shielded variant demonstrating normalized bearing specifications.",featured:true,stockStatus:"Enquire",imageLabel:"6204 / 20 × 47 × 14",specs:{Bore:"20 mm",OD:"47 mm",Width:"14 mm",Seal:"ZZ",Clearance:"C0",Family:"Deep Groove"}},
{id:"bearing-6305-2rs-c3",sku:"6305-2RS-C3",name:"6305 Deep Groove Ball Bearing 2RS C3",slug:"6305-2rs-c3",category:"Bearings",brand:"Sample catalogue",description:"Higher-clearance sample record for C3 filtering and comparison.",featured:true,stockStatus:"Enquire",imageLabel:"6305 / 25 × 62 × 17",specs:{Bore:"25 mm",OD:"62 mm",Width:"17 mm",Seal:"2RS",Clearance:"C3",Family:"Deep Groove"}},
{id:"tool-bt40-er32",sku:"BT40-ER32-100",name:"BT40 ER32 Tool Holder",slug:"bt40-er32-100",category:"CNC Tooling",brand:"Sample catalogue",description:"CNC tooling sample record for taper, collet and gauge-length discovery.",featured:true,stockStatus:"Enquire",imageLabel:"BT40 / ER32",specs:{Standard:"BT",Taper:"BT40",Collet:"ER32","Gauge Length":"100 mm",Coolant:"Enquire"}},
{id:"tool-bt40-side-lock",sku:"BT40-SL-16",name:"BT40 Side-Lock End Mill Holder",slug:"bt40-side-lock-16",category:"CNC Tooling",brand:"Sample catalogue",description:"Side-lock sample record for a second tooling workflow.",stockStatus:"Enquire",imageLabel:"BT40 / Ø16",specs:{Standard:"BT",Taper:"BT40",Bore:"16 mm","Tool Type":"Weldon","Gauge Length":"100 mm"}},
{id:"tool-hsk63a-er32",sku:"HSK63A-ER32",name:"HSK63A ER32 Tool Holder",slug:"hsk63a-er32",category:"CNC Tooling",brand:"Sample catalogue",description:"HSK sample record demonstrating extensible tooling standards.",stockStatus:"Enquire",imageLabel:"HSK63A / ER32",specs:{Standard:"HSK",Taper:"HSK63A",Collet:"ER32","Gauge Length":"100 mm"}}
];
export const categories=["All","Bearings","CNC Tooling"];