import Fastify from"fastify";import cors from"@fastify/cors";import helmet from"@fastify/helmet";import rateLimit from"@fastify/rate-limit";import multipart from"@fastify/multipart";import dotenv from"dotenv";import{z}from"zod";import{catalog,createEnquiry,findBearingProducts,findCncProducts,getProductBySlug,searchProducts}from"./store.js";import{ensureDatabase,databaseEnabled,query}from"./db.js";dotenv.config();
const app=Fastify({logger:true,bodyLimit:2_000_000});const port=Number(process.env.PORT||4000);const origin=process.env.CORS_ORIGIN||"http://localhost:5173";const adminKey=process.env.ADMIN_API_KEY||"change-me";await app.register(cors,{origin});await app.register(helmet);await app.register(rateLimit,{max:120,timeWindow:"1 minute"});await app.register(multipart,{limits:{fileSize:8_000_000,files:5}});
const productSeed=catalog;
async function seedDatabase(){if(!databaseEnabled)return;const count=await query<{count:string}>("SELECT COUNT(*) FROM products");if(Number(count.rows[0].count)>0)return;await query("INSERT INTO categories(id,name,slug) VALUES($1,$2,$3),($4,$5,$6) ON CONFLICT DO NOTHING",["cat-bearings","Bearings","bearings","cat-cnc","CNC Tooling","cnc-tooling"]);await query("INSERT INTO brands(id,name,slug) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",["brand-sample","Sample catalogue","sample-catalogue"]);for(const p of productSeed)await query(`INSERT INTO products(id,sku,name,slug,category_id,brand_id,description,featured,stock_status,image_label,specs) VALUES($1,$2,$3,$4,$5,'brand-sample',$6,$7,$8,$9,$10)`,[p.id,p.sku,p.name,p.slug,p.category==="Bearings"?"cat-bearings":"cat-cnc",p.description,p.featured,p.stockStatus,p.imageLabel,p.specs])}
await ensureDatabase();await seedDatabase();
app.get("/health",async()=>({ok:true,service:"ujjwal-api",mode:databaseEnabled?"postgres":"demo"}));app.get("/api/categories",async()=>({categories:["Bearings","CNC Tooling"]}));app.get("/api/brands",async()=>({brands:["Sample catalogue"]}));
app.get("/api/products",async(request)=>{const q=z.object({search:z.string().optional(),category:z.string().optional()}).parse(request.query);return{products:await searchProducts(q)}});app.get("/api/products/:slug",async(request,reply)=>{const{slug}=z.object({slug:z.string().min(1)}).parse(request.params);const product=await getProductBySlug(slug);if(!product)return reply.code(404).send({error:"Product not found"});return{product}});
app.post("/api/finder/bearings",async request=>({products:await findBearingProducts(z.record(z.string(),z.string()).parse(request.body||{}))}));app.post("/api/finder/cnc",async request=>({products:await findCncProducts(z.record(z.string(),z.string()).parse(request.body||{}))}));
const enquirySchema=z.object({name:z.string().min(2).max(120),company:z.string().max(160).optional().default(""),email:z.string().email().max(200),phone:z.string().min(7).max(40),city:z.string().max(120).optional().default(""),message:z.string().max(4000).optional().default(""),items:z.array(z.object({productId:z.string().min(1),quantity:z.number().int().min(1).max(100000),notes:z.string().max(1000).optional()})).max(100)});
app.post("/api/enquiries",async(request,reply)=>{const payload=enquirySchema.parse(request.body);return reply.code(201).send(await createEnquiry(payload))});
app.post("/api/uploads",async(request,reply)=>{const files=[];for await(const part of request.parts()){if(part.type==="file"){files.push({filename:part.filename,mimetype:part.mimetype,size:(await part.toBuffer()).byteLength})}}if(!files.length)return reply.code(400).send({error:"No file uploaded"});return{files,note:"Production should replace transient handling with private object storage."}});
app.get("/api/admin/catalog",async(request,reply)=>{if(String(request.headers["x-admin-key"]||"")!==adminKey)return reply.code(401).send({error:"Unauthorized"});return{products:databaseEnabled?await searchProducts({}):catalog}});
app.get("/api/admin/enquiries",async(request,reply)=>{if(String(request.headers["x-admin-key"]||"")!==adminKey)return reply.code(401).send({error:"Unauthorized"});if(!databaseEnabled)return{enquiries:[]};const r=await query("SELECT * FROM enquiries ORDER BY created_at DESC LIMIT 200");return{enquiries:r.rows}});
app.setErrorHandler((error,_request,reply)=>{if(error instanceof z.ZodError)return reply.code(400).send({error:"Invalid request",details:error.issues});app.log.error(error);return reply.code(500).send({error:"Unexpected server error"})});
app.listen({port,host:"0.0.0.0"}).then(()=>app.log.info(`UJJWAL API listening on ${port}`));