import{randomUUID}from"node:crypto";import{databaseEnabled,query}from"./db.js";
export type Product={id:string;sku:string;name:string;slug:string;category:string;brand:string;description:string;featured:boolean;stockStatus:"In stock"|"Made to order"|"Enquire";imageLabel:string;specs:Record<string,string>};
export type EnquiryPayload={name:string;company:string;email:string;phone:string;city:string;message:string;items:{productId:string;quantity:number;notes?:string}[]};
export const catalog:Product[]=[
{id:"bearing-6204-2rs",sku:"6204-2RS",name:"6204 Deep Groove Ball Bearing 2RS",slug:"6204-2rs",category:"Bearings",brand:"Sample catalogue",description:"Structured bearing record demonstrating dimension matching, technical filtering and enquiry flow.",featured:true,stockStatus:"Enquire",imageLabel:"6204 / 20 × 47 × 14",specs:{Bore:"20 mm",OD:"47 mm",Width:"14 mm",Seal:"2RS",Clearance:"C0",Family:"Deep Groove"}},
{id:"bearing-6204-zz",sku:"6204-ZZ",name:"6204 Deep Groove Ball Bearing ZZ",slug:"6204-zz",category:"Bearings",brand:"Sample catalogue",description:"Shielded variant demonstrating normalized bearing specifications.",featured:true,stockStatus:"Enquire",imageLabel:"6204 / 20 × 47 × 14",specs:{Bore:"20 mm",OD:"47 mm",Width:"14 mm",Seal:"ZZ",Clearance:"C0",Family:"Deep Groove"}},
{id:"bearing-6305-2rs-c3",sku:"6305-2RS-C3",name:"6305 Deep Groove Ball Bearing 2RS C3",slug:"6305-2rs-c3",category:"Bearings",brand:"Sample catalogue",description:"Higher-clearance sample record for C3 filtering and comparison.",featured:true,stockStatus:"Enquire",imageLabel:"6305 / 25 × 62 × 17",specs:{Bore:"25 mm",OD:"62 mm",Width:"17 mm",Seal:"2RS",Clearance:"C3",Family:"Deep Groove"}},
{id:"tool-bt40-er32",sku:"BT40-ER32-100",name:"BT40 ER32 Tool Holder",slug:"bt40-er32-100",category:"CNC Tooling",brand:"Sample catalogue",description:"CNC tooling sample record for taper, collet and gauge-length discovery.",featured:true,stockStatus:"Enquire",imageLabel:"BT40 / ER32",specs:{Standard:"BT",Taper:"BT40",Collet:"ER32","Gauge Length":"100 mm",Coolant:"Enquire"}},
{id:"tool-bt40-side-lock",sku:"BT40-SL-16",name:"BT40 Side-Lock End Mill Holder",slug:"bt40-side-lock-16",category:"CNC Tooling",brand:"Sample catalogue",description:"Side-lock sample record for a second tooling workflow.",featured:false,stockStatus:"Enquire",imageLabel:"BT40 / Ø16",specs:{Standard:"BT",Taper:"BT40",Bore:"16 mm","Tool Type":"Weldon","Gauge Length":"100 mm"}},
{id:"tool-hsk63a-er32",sku:"HSK63A-ER32",name:"HSK63A ER32 Tool Holder",slug:"hsk63a-er32",category:"CNC Tooling",brand:"Sample catalogue",description:"HSK sample record demonstrating extensible tooling standards.",featured:false,stockStatus:"Enquire",imageLabel:"HSK63A / ER32",specs:{Standard:"HSK",Taper:"HSK63A",Collet:"ER32","Gauge Length":"100 mm"}}
];
function cleanRow(row:any):Product{return{id:row.id,sku:row.sku,name:row.name,slug:row.slug,category:row.category||row.category_name,brand:row.brand||row.brand_name,description:row.description,featured:Boolean(row.featured),stockStatus:row.stock_status,imageLabel:row.image_label,specs:row.specs||{}}}
async function dbProducts(){const r=await query(`SELECT p.*,c.name AS category,b.name AS brand FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id ORDER BY p.featured DESC,p.name ASC`);return r.rows.map(cleanRow)}
export async function searchProducts(args:{search?:string;category?:string}){if(databaseEnabled){let sql=`SELECT p.*,c.name AS category,b.name AS brand FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id WHERE 1=1`;const params:any[]=[];if(args.category){params.push(args.category);sql+=` AND c.name=$${params.length}`}if(args.search){params.push(`%${args.search}%`);const i=params.length;sql+=` AND (p.name ILIKE $${i} OR p.sku ILIKE $${i} OR p.description ILIKE $${i} OR p.specs::text ILIKE $${i})`}sql+=" ORDER BY p.featured DESC,p.name ASC LIMIT 100";return(await query(sql,params)).rows.map(cleanRow)}const needle=(args.search||"").trim().toLowerCase();return catalog.filter(p=>(!args.category||p.category===args.category)&&(!needle||[p.name,p.sku,p.brand,p.category,p.description,...Object.values(p.specs)].join(" ").toLowerCase().includes(needle)));}
export async function getProductBySlug(slug:string){if(databaseEnabled){const r=await query(`SELECT p.*,c.name AS category,b.name AS brand FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id WHERE p.slug=$1 LIMIT 1`,[slug]);return r.rows[0]?cleanRow(r.rows[0]):null}return catalog.find(p=>p.slug===slug)||null}
async function dbFinder(filters:Record<string,string>,category:string){let sql=`SELECT p.*,c.name AS category,b.name AS brand FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE c.name=$1`;const params:any[]=[category];for(const[k,v]of Object.entries(filters)){if(!v)continue;params.push(v);sql+=` AND LOWER(COALESCE(p.specs->>$${params.length},""))=LOWER($${params.length})`;}const r=await query(sql,params);return r.rows.map(cleanRow)}
export async function findBearingProducts(filters:Record<string,string>){if(databaseEnabled)return dbFinder(filters,"Bearings");return catalog.filter(p=>p.category==="Bearings"&&Object.entries(filters).every(([k,v])=>!v||(p.specs[k]||"").replace(/\s+/g,"").toLowerCase()===v.replace(/\s+/g,"").toLowerCase()));}
export async function findCncProducts(filters:Record<string,string>){if(databaseEnabled)return dbFinder(filters,"CNC Tooling");return catalog.filter(p=>p.category==="CNC Tooling"&&Object.entries(filters).every(([k,v])=>!v||(p.specs[k]||"").trim().toLowerCase()===v.trim().toLowerCase()));}
export async function createEnquiry(payload:EnquiryPayload){const id=randomUUID();const number=`UE-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;if(databaseEnabled){await query("BEGIN");try{const valid=await query<{id:string}>(`SELECT id FROM products WHERE id = ANY($1)`,[payload.items.map(i=>i.productId)]);const validIds=new Set(valid.rows.map(r=>r.id));if(payload.items.some(i=>!validIds.has(i.productId)))throw new Error("One or more products are invalid");await query(`INSERT INTO enquiries(id,enquiry_number,name,company,email,phone,city,message) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,number,payload.name,payload.company,payload.email,payload.phone,payload.city,payload.message]);for(const item of payload.items)await query(`INSERT INTO enquiry_items(enquiry_id,product_id,quantity,notes) VALUES($1,$2,$3,$4)`,[id,item.productId,item.quantity,item.notes||""]);await query("COMMIT");return{enquiryNumber:number}}catch(error){await query("ROLLBACK");throw error}}return{enquiryNumber:number}}